### ISSUE TITLE
Error Running Code As Is

### ISSUE THREAD

**Issue by ixodid198** [datawookie/travelling-salesman-map#1]
When this part of the code is run:

```
addresses <- ADDRESSES %>%
  map_dfr(geocode_df) %>%
  mutate(latlon = sprintf("%f+%f", lat, lon)) %>%
  mutate(label = LETTERS[1:nrow(.)]) %>%
  select(label, everything())
```
I get this error:

Information from URL : http://maps.googleapis.com/maps/api/geocode/json?address=115%20St%20Andrew's%20Drive,%20Durban%20North,%20KwaZulu-Natal,%20South%20Africa&sensor=false
Error in geocode(address, output = "all")$results[[1]] : 
  subscript out of bounds

**Comment by datawookie** [comment]
Hello?

Due to changes in the Google Maps Terms of Service, this code will not work without first registering an API key.

Regards,
Andrew.
