### ISSUE TITLE
api key

### ISSUE THREAD

**Issue by majesticnavann** [datawookie/travelling-salesman-map#2]
where in the code would i add the api key ? 
many thanks

**Comment by datawookie** [comment]
Hi @majesticnavann,

Thanks for your enquiry. The code has been updated to answer your question.

Regards,
Andrew.

**Comment by majesticnavann** [comment]
Hi Datawookie,

Really appreciate the code update, thankyou. Did you encounter a curl
timeout issue? , I have registered an api but when running the address
through I get a curl timeout issue.

Have you any ideas on how to fix this?

Best wishes

Majesticnavann

**Comment by datawookie** [comment]
Hi! Yeah, this seems to be a curl issue. I encounter this with multiple packages that rely on curl. If you run it again it should work. Thanks, Andrew.

**Comment by majesticnavann** [comment]
Hi Andrew

Sorry to be a pest , I have manged to get the code working right up until
the last section

map <- get_map(location = c(lon = 30.970622, lat = -29.810094), zoom = 12,
maptype = "roadmap")

ggmap(map, extent = "device") +
  geom_path(data = route, aes(x = lon, y = lat),  colour = "blue", size =
1, alpha = 0.5) +
  geom_point(data = addresses, aes(x = lon, y = lat), size = 3, alpha =
0.75) +
  labs(x = "", y = "")

I am getting the following error code:
Error in aperm.default(map, c(2, 1, 3)) : invalid first argument, must be
an array

I have reinstalled ggmap using devtools and this has not corrected the
issue, have you any ideas ? I really do appreciate your help and time on
this, it is great code and I want to see the end result.

Best wishes

Thomas

**Comment by majesticnavann** [comment]
P.s I have attached the routes that got.
